# Generated by Django 4.0.4 on 2022-05-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
