# Generated by Django 4.0.4 on 2022-05-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0002_picture_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
    ]
