# Generated by Django 4.0.4 on 2022-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0003_picture_clicked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='media')),
                ('is_open', models.BooleanField(default=False)),
                ('is_known', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('clicked', models.BooleanField(default=False)),
            ],
        ),
    ]
