# Generated by Django 4.0.4 on 2022-05-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0004_secretpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.CharField(choices=[('3x3', '3x3'), ('4x4', '4x4'), ('6x5', '6x5')], max_length=100)),
            ],
        ),
    ]
