# Generated by Django 4.0.4 on 2022-05-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_game', '0005_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='matrix',
            field=models.CharField(choices=[('2x2', '2x2'), ('4x4', '4x4'), ('6x4', '6x4'), ('6x6', '6x6')], max_length=100),
        ),
    ]
